import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import path from "node:path";
import {fileURLToPath} from "node:url";
import {entryPreview,potentialDuplicate,recentConfirmed} from "../record-entry-utils.js";
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),"..");
const [app,index,sleep,history]=await Promise.all(["app.js","index.html","sleep-v3.js","history.js"].map(file=>readFile(path.join(root,file),"utf8")));
const milk=(id,time,amount=180,status="confirmed")=>({id,date:"2026-09-04",type:"milk",time,amount,feedType:"配方奶",status,deleted:false});
assert.deepEqual(recentConfirmed([milk("a","08:00"),milk("b","15:20"),milk("c","11:40")],"milk").map(x=>x.id),["b","c","a"],"recent confirmed records must be newest-first");
assert.equal(entryPreview(milk("a","08:00",160)).main,"160ml");
assert.equal(potentialDuplicate(milk("new","15:25",180),[milk("old","15:20",180)])?.id,"old","near-identical milk should warn");
assert.equal(potentialDuplicate(milk("new","15:25",100),[milk("old","15:20",180)]),null,"materially different milk amount should not warn");
const diaper=(id,time,type="便")=>({id,date:"2026-09-04",type:"diaper",time,diaperType:type,status:"confirmed",deleted:false});
assert.equal(potentialDuplicate(diaper("new","12:10"),[diaper("old","12:05")])?.id,"old","near-identical diaper should warn");
assert.match(index,/<details id="dayDetails"[\s\S]*<summary class="timeline-head"/,"Today timeline must be a native collapsible day-detail section");
assert.match(app,/recentEntryMarkup[\s\S]*recordDuplicateWarning/,"frequent record dialogs must surface recent same-type facts and duplicate hint");
assert.match(sleep,/recentSleepMarkup[\s\S]*data-sleep-v3-recent-edit/,"ordinary Sleep must surface recent same-type facts without adding a second overlap detector");
assert.doesNotMatch(history,/最近一次|history-last-occurrence|data-history-last/,"History must not add a separate last-occurrence query UI");
console.log("record entry review UX regressions passed");
